
default: 
	make -f Makefile.cory name=cory_arb4_bandwidth
	#   make -f Makefile.cory_mcs51
	#   make -f Makefile.cory_ddr_ctrl
	#   make -f Makefile.cory name=cory_counter
	#   make -f Makefile.cory name=cory_axiwo_merge
	#   make -f Makefile.cory name=cory_s2p
	#   make -f Makefile.cory name=cory_queue_axi
	#   make -f Makefile.cory name=cory_arb4_bandwidth.v2
	#   make -f Makefile.cory name=cory_route16
	#   make -f Makefile.cory name=cory_rdma2d_yuv
	#   make -f Makefile.cory name=cory_wdma2d_yuv
	#   make -f Makefile.cory name=cory_s2s
	#   make -f Makefile.cory name=cory_wdma2d_rgb
	#   make -f Makefile.cory name=cory_mem
	#   make -f Makefile.cory name=cory_axi4ro_arb2_bw
	#   make -f Makefile.cory name=bory_arb2
	#   make -f Makefile.cory name=cory_axiro_chop
	#   make -f Makefile.cory name=cory_axirw_burst_chop
	#   make -f Makefile.cory name=cory_axiwo_wrap2incr
	#   make -f Makefile.cory name=cory_axiwo_wrap_chop
	#   make -f Makefile.cory name=cory_axiro_wrap_chop

clean:
	rm -rf ./INCA*

